# Generated by Django 2.0.4 on 2018-05-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('subject', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('to', models.CharField(max_length=50)),
                ('departing', models.CharField(max_length=50)),
                ('departure_date', models.DateTimeField()),
                ('passengers', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], default='1', max_length=30)),
                ('flight_type', models.CharField(choices=[('one way', 'One Way'), ('round trip', 'Round Trip')], default='one way', max_length=30)),
                ('cabin_class', models.CharField(choices=[('business', 'Business'), ('economy', 'Economy'), ('premium', 'Premium'), ('first', 'First')], default='economy', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
                ('possible_location', models.CharField(max_length=30)),
                ('check_in_date', models.DateTimeField()),
                ('check_out_date', models.DateTimeField()),
                ('number_of_rooms', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='1', max_length=30)),
                ('occupancy', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='1', max_length=30)),
                ('hotel_category', models.CharField(choices=[('first', 'First Class Hotel'), ('luxury', 'Luxury Hotel'), ('standard', 'Standard Hotel'), ('tourist', 'Tourist Hotel')], default='first', max_length=30)),
            ],
        ),
    ]
