# Generated by Django 2.0.4 on 2018-05-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GCTM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='flight',
            name='phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='phone',
            field=models.CharField(max_length=30),
        ),
    ]
